### PR TITLE
Fix: update minimist version

### PR DESCRIPTION
**Pull request by vileppanen**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[ X ] Other, please explain:

There's a reported prototype pollution vulnerability in `minimist`, versions under 1.2.2 https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764

**What changes did you make? (Give an overview)**

- fixed failing tests
- updated minimist version to ^1.2.2

**Which issue (if any) does this pull request address?**

This might resolve this autogenerated issue https://github.com/standard/standard-engine/issues/211
The build seems to fail due to the failing tests, which should be fixed in this PR

**Is there anything you'd like reviewers to focus on?**

Relied on running tests, and dummy local cli setup to smoke test this. No failing tests, nor crashing cli, therefore assumed, the update didn't break anything. If someone has more detailed insight on this, whether I overlooked something, would gladly hear 👍

### CODE REVIEW

**Comment by vileppanen** [comment]
Ping @feross, any chance to look into this? It seems the greenkeeper was already trying to update the minimist version, but failed due to those failing tests, which should be corrected in this one.

**Comment by LinusU** [comment]
Hi @vileppanen, very sorry for the delay here. It seems like we arrived in the same fix for the tests, I didn't see this when I fixed it in #219 so sorry for not cherry-picking your commit! 🙈 ❤️ 

I did a large PR which bumps all dependencies and a bunch of other cleanup here: #220 

Again, sorry for just making the changes myself, I was doing all the other little changes and didn't want the package-lock committed since it won't be used when this package is installed by someone else, so I figured it was easier to just roll it in to everything else.

Thank you for opening the PR! I promise to be quicker to respond next time 😉

**Comment by vileppanen** [comment]
> Hi @vileppanen, very sorry for the delay here. It seems like we arrived in the same fix for the tests, I didn't see this when I fixed it in #219 so sorry for not cherry-picking your commit! 🙈 ❤️
> 
> I did a large PR which bumps all dependencies and a bunch of other cleanup here: #220
> 
> Again, sorry for just making the changes myself, I was doing all the other little changes and didn't want the package-lock committed since it won't be used when this package is installed by someone else, so I figured it was easier to just roll it in to everything else.
> 
> Thank you for opening the PR! I promise to be quicker to respond next time 😉

No worries 👍, main goal achieved anyways 😄

**Comment by feross** [comment]
Just seeing this now. Thanks everyone!

**Pull request closed without merging**
