### PR TITLE
feat(cli): add `--ignore` option

### PR DESCRIPTION
**Pull request by romkhub**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Added `--ignore` flag support.
I'd like to run linter separately for unit-tests:
```
"lint:src": "ts-standard src -p tsconfig.json --ignore \"src/**/*.test.ts\"",
"lint:unit": "ts-standard \"src/**/*.test.ts\" -p tsconfig.test.json",
```

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**
I had to change `engines` setup in `package.json` because `check:installed-check` script fails otherwise:
```diff
-    "node": "^12.22.0 || ^14.17.0 || >=16.0.0"
+    "node": "^14.18.0 || >=16.0.0"
```
this comes from the following `dependency-check` commit - https://github.com/dependency-check-team/dependency-check/commit/e88ae34537ee9dadbf472ffe7b32285f90fd99eb

I'd love to see this feature within the current major version, but I doubt this is going to be blessed due to drop of node-12. Is there an option to avoid a major version bump, or should I just go ahead and make it `"version": "16.0.0"`?

### CODE REVIEW

**Review by Divlo — APPROVED** [review]
Thanks!
I honestly thought, we already supported the `--ignore` option. :smile: 
Overall changes, looks good to me. :+1:

About the `check:installed-check`, I'd rather still support Node.js v12 to avoid the breaking change and in `package.json`, set `"dependency-check": "5.0.0-4",`, without the `^`.
This will allow us, to release it as `standard-engine` v15.1.0 and also release it quicker for the different engines like `ts-standard`. Thoughts @voxpelli?

**Comment by voxpelli** [comment]
Should work to just use the ignore flag in installed-check to have it ignore dependency-check, the dev deps are not as crucial and dependency-check will quit silently on unsupported node versions

**Review by LinusU — APPROVED** [review]
Neat! 👍

**Comment by romkhub** [comment]
Thank you @voxpelli
done!

**Comment by romkhub** [comment]
Good day
Thank you a lot for accepting this PR
Could I kindly ask anyone to release the `15.1.0` version?

**Comment by voxpelli** [comment]
I'll try to get to it next week, I'm crunching g towards a Christmas deadline right now, if it hasn't been released by next week, then ping me here again

(I want GitHub to add a snooze feature 😝)

**Comment by Divlo** [comment]
friendly ping @voxpelli

**Comment by romkhub** [comment]
friendly ping @voxpelli  ❤️

**Comment by voxpelli** [comment]
Released in [`15.1.0`](https://github.com/standard/standard-engine/releases/tag/v15.1.0), thanks 🙏

**Pull request merged**
