### PR TITLE
Allow passing in a custom linter to `cli`

### PR DESCRIPTION
**Pull request by Raynos**
This allows a downstream project like `tsdocstandard` to subclass the `Linter`

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

Allow passing in a custom linter object to `cli()`

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by Raynos** [comment]
The goal for this PR is to be able to pass in a subclass of `LintEngine`

This way I can change the default files to be linted, which are currently `*.js` to include `*.d.ts` as well since my `tsdocstandard` variant wants to lint JavaScript and definition files.

**Comment by Raynos** [comment]
Could someone take a look at this small patch :sweat_smile:

cc @LinusU @toddbluhm

**Comment by LinusU** [comment]
Sorry for not getting to this earlier 🙈 

Unfortunately I'm not too familiar with this codebase, so I'm wondering if this might expose something that we aren't expecting to be in the public API, and thus we might make breaking changes to it. It seems like the `Linter` class is already exposed here though:

https://github.com/standard/standard-engine/blob/460f258b297ecde90d21bb84e86996c26f910b23/index.js#L3

With that said, I think that this should be good 👍

**Comment by Raynos** [comment]
What's the preferred flow on the repo. I happen to have commit access, so I can happily merge and bump minor version. I don't have permissions to publish

**Comment by LinusU** [comment]
I think that I have publish access, so I can cut a release

We should probably write down the process somewhere and make sure that you have publish access as well though. This really applies to the entire org

**Pull request merged**
